// Do not edit!  This file was autogenerated 
// by the .\comptime.bat batch file 
// 
const char* compbranch = "quest"; 
const char* comprevision = "002fb4aa"; 
const char* compnote = "vr-move-where-you-look-and-snap-turning"; 
